---
- name: Проверка статуса службы управления конфигурацией drweb-configd
  systemd:
    name: drweb-configd
  register:
    drweb_configd

- name: Копирование установочного файла Dr.Web Workstation 11 для Linux
  copy:
    src: drweb-workstations_11.1.3-2201141226+mo~linux_amd64.run
    dest: /tmp
    mode: '0755'

- name: Установка Dr.Web Workstation 11 для Linux
  shell: |
    /tmp/drweb-workstations_11.1.3-2201141226+mo~linux_amd64.run -- --non-interactive
    drweb-configure session enable
  when:
    drweb_configd.status.ActiveState != "active"

- name: Создание символической ссылки на модуль аутентификации pam_drweb_session.so
  file:
    src: /opt/drweb.com/lib/x86_64-linux-gnu/pam/pam_drweb_session.so
    dest: /lib/security/pam_drweb_session.so
    state: link

- name: Создать каталог карантина
  file:
    path: '{{ quarantine }}'
    state: directory
    mode: '700'

- name: Установка мандатных прав каталога карантина
  shell:
    pdpl-file 3:0:0:ccnr '{{ quarantine }}'

- name: Разрешение службе управления конфигурацией drweb-configd использовать механизм privsock
# Добавить строки, только если они отсутствуют
  lineinfile:
    state: present
    dest: /etc/parsec/privsock.conf
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  loop:
    - line: /opt/drweb.com/bin/drweb-configd
      regexp: ^/opt/drweb.com/bin/drweb-configd$
    - line: /opt/drweb.com/bin/drweb-configd.real
      regexp: ^/opt/drweb.com/bin/drweb-configd.real$

- name: Копирование ключевого файла
  copy:
    src: drweb32.key
    dest: /etc/opt/drweb.com/

- name: Перезапуск службы управления конфигурацией drweb-configd
  service:
    name: drweb-configd
    state: restarted

# Только после активации лицензии на сервере Dr.Web
# TODO Сделать проверку ошибки скачивания сертификата, на случай, если ЦУ САВЗ не доступен
- name: Подключение хоста к антивирусной сети
  shell: |
    wget https://{{ arm_abi_addr }}:9081/install/windows/drwcsd-certificate.pem --no-check-certificate -P /tmp
    drweb-ctl esconnect {{ arm_abi_addr }} --Certificate /tmp/drwcsd-certificate.pem --Newbie
