---
- name: Получение имени учетной записи администратора безопасности
  shell:
    id -n -u 1000
  register: admin_name
  # имя учетной записи в {{ admin_name.stdout }}

- name: Получение имени хоста
  shell:
    hostname
  register: host_name
  # имя учетной записи в {{ host_name.stdout }}

- name: Получение ip-адреса АРМ-АБИ из инвентори
  set_fact:
    arm_abi_addr: "{{ hostvars['arm-abi']['ansible_host'] }}"

# По дефолту не устанавливается локаль en_US.UTF-8, поэтому доустанавливаем
- name: Добавление локали en_US.UTF-8
  lineinfile:
    path: /etc/locale.gen
    regexp: en_US.UTF-8
    line: en_US.UTF-8 UTF-8

- name: Генерация локалей
  shell:
    locale-gen

- name: Изменение имени хоста в /etc/hosts
  replace:
    path: /etc/hosts
    regexp: '127.0.1.1(\s)+(\S)+'
    replace: '127.0.1.1\1{{ ansible_facts["nodename"] }}'

- name: Добавление IP-адресов хостов в /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"

- name: Выполнение дополнительных задач по конфигурированию
  include_tasks: "{{ item }}"
  loop:
    - afick.yml
    - secure.yml

